// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAenhV8fICy8h9_jS9c6vz9WHfpcLVAY34',
    appId: '1:1042180423758:web:071425c9dd45ab908e031f',
    messagingSenderId: '1042180423758',
    projectId: 'pyacademy-a29e2',
    authDomain: 'pyacademy-a29e2.firebaseapp.com',
    storageBucket: 'pyacademy-a29e2.firebasestorage.app',
    measurementId: 'G-SSJSV9K91Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCklPj5Ov6ZHP64ya65Nz7OwggMbIbn4qA',
    appId: '1:1042180423758:android:a3241f2b2804d45a8e031f',
    messagingSenderId: '1042180423758',
    projectId: 'pyacademy-a29e2',
    storageBucket: 'pyacademy-a29e2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDEYKk7QNq8POtAJ_XBV1eJ3GH1M6z5C0',
    appId: '1:1042180423758:ios:1512d4220ebc46588e031f',
    messagingSenderId: '1042180423758',
    projectId: 'pyacademy-a29e2',
    storageBucket: 'pyacademy-a29e2.firebasestorage.app',
    iosBundleId: 'com.example.pyacademy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDEYKk7QNq8POtAJ_XBV1eJ3GH1M6z5C0',
    appId: '1:1042180423758:ios:1512d4220ebc46588e031f',
    messagingSenderId: '1042180423758',
    projectId: 'pyacademy-a29e2',
    storageBucket: 'pyacademy-a29e2.firebasestorage.app',
    iosBundleId: 'com.example.pyacademy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAenhV8fICy8h9_jS9c6vz9WHfpcLVAY34',
    appId: '1:1042180423758:web:bfd0dc1c999b3ccd8e031f',
    messagingSenderId: '1042180423758',
    projectId: 'pyacademy-a29e2',
    authDomain: 'pyacademy-a29e2.firebaseapp.com',
    storageBucket: 'pyacademy-a29e2.firebasestorage.app',
    measurementId: 'G-VS52D44HCC',
  );

}